### ISSUE TITLE
Dialog windows of modules crash application

### ISSUE THREAD

**Issue by dmarszk** [Wisling/tibiaauto#1]
According to Wisling, any child afx window opened by dialog window ends up crashing TA.

**Comment by dmarszk** [comment]
I'm actually finding it hard to reproduce when using eaca85de053253d7e6ccdfc93bcaf60a22e7dc7b as head. @Wisling please advise.

**Comment by Wisling** [comment]
I checked and it's only in the debug build of TA.

**Comment by dmarszk** [comment]
Could you provide me with steps to reproduce?

2016-04-05 14:44 GMT+02:00 Wisling notifications@github.com:

**Comment by Wisling** [comment]
Yeah, if you don't experience it, then let me know.
Build TA under Debug.
Run TA & connect to any Tibia session.
Go to spells, healing, and try and edit the exura sio Heal List.  If there is an error before the window appears, then that's what I'm referring to.

**Comment by dmarszk** [comment]
Thanks.
I found the culprit. All modules are being derived from CWinApp. It's pointless, because all modules are actually DLLs acting as hidden dialogs. CWinApp makes MFC think each module is a separate application, and tries to assign the child dialog boxes to it. I'll fix it after merging current patches.

**Comment by dmarszk** [comment]
Fixed in d08e5d843d05cfa21e42b47a5af5112c0a2a8193

**Comment by Wisling** [comment]
That probably explains why tabbing didn't work either.  I may need to undo some work-arounds :P
