### ISSUE TITLE
Make backpack opener a separate module

### ISSUE THREAD

**Issue by dmarszk** [Wisling/tibiaauto#30]
Having it in autologin is a pretty bad idea. Move it to a separate module... or create a built-in python script for it!

**Comment by Wisling** [comment]
Adding less than 10 lines of code made it work in the autologin.  It was destined to be.
Besides, backpacks only accidentally close in an unavoidable way when the connection drops.  User awareness of such a small but useful feature can be done through serendipitous discovery or in the forums if needed.
Can I close this?

**Comment by dmarszk** [comment]
Oh well. I just had a dream about separating not quite related
functionalities into separate modules. But sure, do close it if you think
it should stay there. I doubt I would be having any time in the upcoming
months anyway. :S

29 sie 2016 18:39 "Wisling" notifications@github.com napisał(a):
