### ISSUE TITLE
Help me to update to 10.95

### ISSUE THREAD

**Issue by negrix** [Wisling/tibiaauto#61]
Hello,

I install tibia auto for 10.92, and download the tibiaauto in github, i copy the archives of tibiaauto-pub to tibiaauto folder, and when i open tibia, and tibia auto in administrator mode the tibia crash in 10 seconds.. whats is happening?

Sorry my poor english. 

Thank you.

**Comment by felipetnh** [comment]
Dude...
First of all: you should be posting this issue on the forums, not here.
Second: what are you trying to do? You talk about TA 10.95 on the title and talk about TA 10.92 on the issue.
Third: you have got to give us more information, like exactly your steps, pics of the crash, if it's for an OT, etc.

**Comment by dmarszk** [comment]
^ What he said.
