### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by felipetnh** [Wisling/tibiaauto#65]
Does anyone have the contact info of Wateva?
The website is offline now and I think he is the only one capable of putting it back online.
The problem is that he didn't visit the forum since March or April.
So I'm guessing he is not aware that the website is offline now.
If someone could just email him that would be great!

@Wisling

**Comment by Wisling** [comment]
I'm on it!

**Comment by felipetnh** [comment]
Yay!
It's back online!
Did you talk to Wateva, @Wisling?

**Comment by felipetnh** [comment]
Erm...
It's back offline with sql problems... haha

**Comment by Wisling** [comment]
That was shortlived. It's the same problem.  I'll ask if he can look into it the cause.

**Comment by felipetnh** [comment]
It's back online again... :D
Let's hope it stays that way... =D

**Comment by felipetnh** [comment]
Back offline. =/
@Wisling

**Comment by felipetnh** [comment]
Back online. :)
