### ISSUE TITLE
TA is not looting

### ISSUE THREAD

**Issue by felipetnh** [Wisling/tibiaauto#66]
http://tibiaauto.net/forum/viewtopic.php?f=1&t=1018898

**Comment by felipetnh** [comment]
Anyone got a chance to take a look at this? :)
@Wisling @Rebell

**Comment by Wisling** [comment]
Took a look at it, and it seems CIPSoft no longer tells the Tibia client when a creature reaches 0 health.  But it looks like there are other variables that can be used to make this inference.
