### ISSUE TITLE
Just question please

### ISSUE THREAD

**Issue by smurf4444** [Wisling/tibiaauto#72]
Hello; i have learned c++ almost finished it. i have a problem with TA update which is Where  can i get the correct values after Tibia is updated 
Well Check this link please. 
http://tibiaauto.net/forum/viewtopic.php?f=4&t=1019080
I wish you answer me :)

Thanks
@Rebell @Wisling

**Comment by felipetnh** [comment]
Just tagging @Wisling and @Rebell directly on this one. :)

**Comment by smurf4444** [comment]
I got it from friends :)
Thanks anyway

**Comment by jlcvp** [comment]
@smurf4444 can you update the file and make a pull request here?
